/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Carmen
 */
public class ModeloInicio extends javax.swing.JFrame {
  

    /**
     * Creates new form ModeloInicio
     */
    public ModeloInicio() {
        initComponents();
    }


     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelAPP = new javax.swing.JPanel();
        Incio = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bt_visualizar_usuario = new javax.swing.JButton();
        pUsuario = new javax.swing.JPanel();
        jLabel74 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_usuario = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        NombrePersonatxt = new javax.swing.JTextField();
        dnitext = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        DniLabel = new javax.swing.JLabel();
        calletext = new javax.swing.JTextField();
        ciudadtext = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        codig_postext = new javax.swing.JTextField();
        penalizacointxt = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        btnInsertlector = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Buscar_usuer = new javax.swing.JButton();
        NCarnetEdit = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        text_eliminar = new javax.swing.JTextField();
        btn_eliminar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelAPP.setLayout(new java.awt.CardLayout());

        jLabel1.setText("BIBLIOTECA");

        bt_visualizar_usuario.setText("VISUALIZAR LECTORES");

        javax.swing.GroupLayout IncioLayout = new javax.swing.GroupLayout(Incio);
        Incio.setLayout(IncioLayout);
        IncioLayout.setHorizontalGroup(
            IncioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IncioLayout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addGroup(IncioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_visualizar_usuario)
                    .addGroup(IncioLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel1)))
                .addContainerGap(569, Short.MAX_VALUE))
        );
        IncioLayout.setVerticalGroup(
            IncioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IncioLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(49, 49, 49)
                .addComponent(bt_visualizar_usuario)
                .addContainerGap(552, Short.MAX_VALUE))
        );

        PanelAPP.add(Incio, "card3");

        jLabel74.setText("INFORMACION USUARIOS");

        tabla_usuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla_usuario);

        jLabel14.setText("Nombre");

        NombrePersonatxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombrePersonatxtActionPerformed(evt);
            }
        });

        jLabel2.setText("DNI");

        DniLabel.setText("Calle");

        calletext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calletextActionPerformed(evt);
            }
        });

        ciudadtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ciudadtextActionPerformed(evt);
            }
        });

        jLabel18.setText("Ciudad");

        jLabel15.setText("Codigo_Postal");

        codig_postext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codig_postextActionPerformed(evt);
            }
        });

        penalizacointxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penalizacointxtActionPerformed(evt);
            }
        });

        jLabel16.setText("Penalización");

        btnInsertlector.setText("Guardar");
        btnInsertlector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertlectorActionPerformed(evt);
            }
        });

        jLabel3.setText("ELIMINAR");

        Buscar_usuer.setText("Buscar");

        jLabel4.setText("Introduce el Nº de carnet del usuario a eliminar: ");

        text_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_eliminarActionPerformed(evt);
            }
        });

        btn_eliminar.setText("Eliminar");

        javax.swing.GroupLayout pUsuarioLayout = new javax.swing.GroupLayout(pUsuario);
        pUsuario.setLayout(pUsuarioLayout);
        pUsuarioLayout.setHorizontalGroup(
            pUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pUsuarioLayout.createSequentialGroup()
                .addGroup(pUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pUsuarioLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(pUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pUsuarioLayout.createSequentialGroup()
                                .addGroup(pUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pUsuarioLayout.createSequentialGroup()
                                        .addGroup(pUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(DniLabel)
                                            .addComponent(jLabel15))
                                        .addGap(23, 23, 23)
                                        .addGroup(pUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(pUsuarioLayout.createSequentialGroup()
                                                .addComponent(codig_postext, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(32, 32, 32)
                                                .addComponent(jLabel16)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(pUsuarioLayout.createSequentialGroup()
                                                .addComponent(calletext, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel18)
                                                .addGap(36, 36, 36))))
                                    .addGroup(pUsuarioLayout.createSequentialGroup()
                                        .addGap(297, 297, 297)
                                        .addComponent(jLabel2)
                                        .addGap(36, 36, 36)))
                                .addGroup(pUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dnitext, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(pUsuarioLayout.createSequentialGroup()
                                            .addComponent(penalizacointxt, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(26, 26, 26)
                                            .addComponent(btnInsertlector, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(17, 17, 17))
                                        .addComponent(ciudadtext, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(pUsuarioLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel74)))
                    .addGroup(pUsuarioLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(pUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(27, 27, 27)
                        .addComponent(text_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_eliminar))
                    .addGroup(pUsuarioLayout.createSequentialGroup()
                        .addGap(396, 396, 396)
                        .addComponent(Buscar_usuer)
                        .addGap(18, 18, 18)
                        .addComponent(NCarnetEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pUsuarioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(345, Short.MAX_VALUE))
            .addGroup(pUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pUsuarioLayout.createSequentialGroup()
                    .addGap(46, 46, 46)
                    .addComponent(jLabel14)
                    .addGap(54, 54, 54)
                    .addComponent(NombrePersonatxt, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(675, Short.MAX_VALUE)))
        );
        pUsuarioLayout.setVerticalGroup(
            pUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pUsuarioLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel74)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(pUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Buscar_usuer)
                    .addComponent(NCarnetEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dnitext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(19, 19, 19)
                .addGroup(pUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calletext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DniLabel)
                    .addComponent(ciudadtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addGroup(pUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codig_postext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(penalizacointxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(btnInsertlector))
                .addGap(27, 27, 27)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(pUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(text_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_eliminar))
                .addContainerGap(250, Short.MAX_VALUE))
            .addGroup(pUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pUsuarioLayout.createSequentialGroup()
                    .addGap(223, 223, 223)
                    .addGroup(pUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(NombrePersonatxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(415, Short.MAX_VALUE)))
        );

        PanelAPP.add(pUsuario, "card11");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelAPP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelAPP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NombrePersonatxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombrePersonatxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombrePersonatxtActionPerformed

    private void codig_postextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codig_postextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codig_postextActionPerformed

    private void btnInsertlectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertlectorActionPerformed

    }//GEN-LAST:event_btnInsertlectorActionPerformed

    private void calletextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calletextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calletextActionPerformed

    private void penalizacointxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penalizacointxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_penalizacointxtActionPerformed

    private void ciudadtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ciudadtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ciudadtextActionPerformed

    private void text_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_eliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_eliminarActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Buscar_usuer;
    private javax.swing.JLabel DniLabel;
    public javax.swing.JPanel Incio;
    public javax.swing.JTextField NCarnetEdit;
    public javax.swing.JTextField NombrePersonatxt;
    public javax.swing.JPanel PanelAPP;
    public javax.swing.JButton bt_visualizar_usuario;
    public javax.swing.JButton btnInsertlector;
    public javax.swing.JButton btn_eliminar;
    public javax.swing.JTextField calletext;
    public javax.swing.JTextField ciudadtext;
    public javax.swing.JTextField codig_postext;
    public javax.swing.JTextField dnitext;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel74;
    public javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JPanel pUsuario;
    public javax.swing.JTextField penalizacointxt;
    public javax.swing.JTable tabla_usuario;
    public javax.swing.JTextField text_eliminar;
    // End of variables declaration//GEN-END:variables

  
}
